# Generated by Django 5.1.1 on 2024-09-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название тарифа')),
                ('price', models.FloatField(verbose_name='Цена за кубометр')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('number', models.CharField(max_length=255, verbose_name='Номер дома')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('city', 'street', 'number'), name='unique_city_street_number')],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.building', verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Показания счетчика')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.apartment', verbose_name='Квартира')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.tariff', verbose_name='Название тарифа')),
            ],
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_building_number'),
        ),
    ]
