services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
     - 8000:8000
    restart: always

  postgres:
    image: postgres:16
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always


volumes:
  pg_data: