services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - static:/app/staticfiles
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - static:/app/staticfiles
    ports:
      - 80:8080
    depends_on:
      - backend
    restart: always


volumes:
  pg_data:
  static: