services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    restart: always

  celery:
    build: ./backend
    env_file:
      - ./backend/.env
    entrypoint: celery -A settings worker -l INFO
    depends_on:
      - backend
      - redis
    restart: always

  flower:
    build: ./backend
    env_file:
      - ./backend/.env
    entrypoint: celery -A settings flower
    ports:
      - 5555:5555
    depends_on:
      - celery
      - redis
    restart: always

  postgres:
    image: postgres:16
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - static:/app/staticfiles
    ports:
      - 80:8080
    depends_on:
      - backend
    restart: always


volumes:
  pg_data:
  static: