# Generated by Django 5.1.1 on 2024-09-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Квартплата')),
                ('date_from', models.DateField(verbose_name='Дата от (включительно)')),
                ('date_to', models.DateField(verbose_name='Дата до (не включительно)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.apartment', verbose_name='Квартира')),
            ],
        ),
    ]
